apiVersion: v1
kind: Service
metadata:
  name: cs-pov-victim
spec:
  selector:
    app.kubernetes.io/name: cs-pov-victim
  clusterIP: None
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
